### ISSUE TITLE
[refresh_cache.py] All games in one connection.

### ISSUE THREAD

**Issue by Farmaceutico** [Yepoleb/gogdb#1]
If you want, you can use limit=9999 "https://www.gog.com/games/ajax/filtered?mediaType=game&page={}&sort=bestselling&limit=9999", so, you have all results in one page.

**Comment by Yepoleb** [comment]
Thanks, that's a great idea!

**Comment by Yepoleb** [comment]
Implemented in cec5ebcdeb492317897e5eaaa3f4e24c1619f3f1

**Comment by Yepoleb** [comment]
They just put in a limit, but it was nice while it lasted :)
