### ISSUE TITLE
What does Generation mean? What do 1 and 2 refer to?

### ISSUE THREAD

**Issue by fyzzy1943** [Yepoleb/gogdb#19]
![1.jpg](https://s2.loli.net/2023/07/08/y3h5UnHk69detPX.jpg)

Just like in this screenshot

**Comment by Yepoleb** [comment]
GOG has two versions of its content system that use entirely different file structures. They are referred to as generations to avoid confusion with the game versions. If you choose an older game you might still be able to find generation 1 builds on GOG DB. You will notice the build information is completely different to newer gen 2 builds.
