### ISSUE TITLE
Add the file size to product pages 

### ISSUE THREAD

**Issue by Keith94** [Yepoleb/gogdb#2]
For example, Dragon's Dogma: Dark Arisen should have "19.4 GB" displayed on the product page: http://gogdb.yepoleb.me/product/1242384383

**Comment by coughlanio** [comment]
This should be possible as the download size is available on the API via downloads.installers.total_size - but this appears to be slightly off from what GOG display on their page - Dark Arisen being 20.8 GB compared to the API.

**Comment by Yepoleb** [comment]
Thanks for the suggestion! I wanted to add the install size once content system integration is completed, but total download size may be interesting as well.
