### ISSUE TITLE
Question: GOG build ID

### ISSUE THREAD

**Issue by ViperCode7** [Yepoleb/gogdb#20]
Hi
When a game gets updated it gets a build ID, a number in parentheses, like for Cyberpunk it's right now (68508). Is this build number anywhere? The installer file name is setup_cyberpunk_2077_build_4940722change_6460039_0_(64bit)_(68508) so it has no version in it but on the build tab on gogdb, there's nothing about it... neither the file name, nor that gog build ID, as of now it's just a 2.02.

**Comment by Yepoleb** [comment]
I don't know where that number comes from and it's not even consistently present.
