### ISSUE TITLE
# scripts/run.sh assets not working

### ISSUE THREAD

**Issue by PnYMaT** [Yepoleb/gogdb#23]
Hi, the command : # scripts/run.sh assets
is not working. assets don't exist.

I fix with adding this in run.sh

assets)
    python3 gogdb/application/assets.py "$@"

Thanks for your works, it run nice on my Debian 12 self hosted server, i use your backup_v3 as a starting point.

**Comment by Yepoleb** [comment]
Hello, this command is not needed anymore since assets are served individually and not in a package. I have updated the readme. Thanks for the report.
