### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by shakeyourbunny** [Yepoleb/gogdb#3]
Hello,

would be neat, if you would provide a RSS feed for the changes.

Thanks!

**Comment by Yepoleb** [comment]
Yeah, I'm surprised I haven't thought of this earlier. Definitely planned.

**Comment by shakeyourbunny** [comment]
Any news on the RSS feed feature?

**Comment by Yepoleb** [comment]
No, I'm currently working on other GOG stuff, but it'll most likely come with the next update.

**Comment by Yepoleb** [comment]
It's now available at /changelog.xml. Let me know if it works with your RSS reader.

**Comment by Keith94** [comment]
Can confirm it works with Feedly. 👍 
You should make it so browsers can detect the feed is available (maybe needs different format).

**Comment by Shiryou** [comment]
Autodiscovery should work with:

```
<link rel="alternate" type="application/rss+xml" title="RSS Feed for GOGDB" href="/changelog.xml" />
```

**Comment by Yepoleb** [comment]
I know how it works, I just didn't have enough time to add it last night.

**Comment by Yepoleb** [comment]
Feed detection is added.

**Comment by shakeyourbunny** [comment]
Nice, thanks for your efforts.

Now slurping it with r2e to my mailbox (I prefer reading RSS reading via mail since the death of the Google RSS Reader)
