### ISSUE TITLE
Since 1 october 2018 all items wrongly marked as unlisted on gogdb

### ISSUE THREAD

**Issue by Vednier** [Yepoleb/gogdb#6]
Its probably because of "love-to-hate" design upgrade GOG.com undergone. Changelog data is still coming and seems to be valid, but price monitoring is not working anymore.

**Comment by Yepoleb** [comment]
I am aware, update is planned soon.

**Comment by TheDcoder** [comment]
Sad to see that price monitoring is not working as well :disappointed:

I hope we can get this fixed soon!
