### ISSUE TITLE
Installer checksums

### ISSUE THREAD

**Issue by 07416** [Yepoleb/gogdb#7]
Can checksums added for the game installers (and preferably "goodies")? The now-dormant [gogwiki.com has MD5 hashes for games when available](https://www.gogwiki.com/wiki/The_Witcher_Enhanced_Edition:_Director%27s_Cut).

Obviously the checksums have to be crowdsourced — I don't know if GOG DB is associated with any GOG account.

**Comment by Yepoleb** [comment]
Crowdsourcing information is not something I want to get into with this project, sorry.

**Comment by 07416** [comment]
@Yepoleb  Does GOG DB have any bot account with owned games, like SteamDB does?

**Comment by Yepoleb** [comment]
I do use a bot account, but it doesn't own any games.
