### ISSUE TITLE
Game changelogs

### ISSUE THREAD

**Issue by 07416** [Yepoleb/gogdb#8]
Is it possible to display the GOG's internal game changelogs on GOG DB pages?

[Shadow Warrior 2](https://www.gog.com/game/shadow_warrior_2) as an example (partial changelog):

> Patch 1.1.14.0 (19 February 2018)
> 
>     Holiday patch is being rolled back. You can still access "Master Wang, please save the Christmas!" mission by using a snowglobe placed right under the TV set in Wang Cave
> 
> Patch 1.1.13.0 (21 December 2017)
> 
>     Lo Wang's home now looks like it should when the snow falls.
>     Special winter mission is now available in the game world after killing the first boss.
>     Help Lo Wang save Christmas! Get messy with Krampus the Bad Santa and win a unique weapon!
> 
> Patch 1.1.11.1 (23 August 2017)
> The Bounty Hunt - Part 2 DLC
> 
>     adds weapons Chill Factor and TBSM (Tactical Bullet Spewing Machine)
>     adds three new perks
>     adds thirteen new missions
> 
> Patch 1.1.10.1 (17 March 2017)
> The Bounty Hunt - Part 1 DLC
> 
>     Fourteen new bounty missions that can be found in Wang's Cave on a bounty board
>     Two new weapons: Medusa gun and EX-GF01 minigun
>     Four new perks
>     It's free!

**Comment by Yepoleb** [comment]
Yes, that is possible, I just haven't gotten around to implementing it in the UI.

**Comment by Yepoleb** [comment]
Implemented in 6661aad4d161c3fae51ae6a8330233a3f58a735c
