### ISSUE TITLE
No infos about Linux games ?

### ISSUE THREAD

**Issue by awsms** [Yepoleb/gogdb#9]
Are you gonna implement it at some point, or it's not in your planning ?

**Comment by Yepoleb** [comment]
What exactly are you expecting?

**Comment by awsms** [comment]
> What exactly are you expecting?

Build and versioning infos?

**Comment by Yepoleb** [comment]
GOG does not have Linux builds, it only has downloads. These are tracked in GOG DB.

**Comment by awsms** [comment]
> GOG does not have Linux builds

I had no idea about this. I thought you only parsed MacOS/Win builds infos.
